service: aws-python-simple-http-endpoint
frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-1
  runtime: python3.8
  environment:
    FIRETAIL_API_TOKEN: ${param:firetail-token}
    FIRETAIL_EXTENSION_DEBUG: TRUE
    AWS_LAMBDA_EXEC_WRAPPER: /opt/firetail-wrapper.sh
  tracing: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

plugins:
  - serverless-plugin-tracing

functions:
  currentTime:
    handler: handler.endpoint
    layers:
      - arn:aws:lambda:eu-west-1:453671210445:layer:firetail-extension-x86_64-v1-0-1:1
    events:
      - httpApi:
          path: /time
          method: get
