service: aws-python-simple-http-endpoint
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  environment:
    FIRETAIL_API_URL: https://api.logging.eu-west-1.sandbox.firetail.app/logs/bulk
    FIRETAIL_API_TOKEN: your-api-token

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: /time
          method: get

plugins:
  - serverless-offline
