name: Build & publish

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
  
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ 'amd64', 'arm64' ]
    steps:
      - uses: actions/checkout@v3

      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build & package layers (amd64 & arm64)
        run: |
          make package ARCH=${{ matrix.arch }} VERSION=$RELEASE_VERSION

      - name: Upload package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: firetail-lambda-extension-${{ matrix.arch }}-${{ env.RELEASE_VERSION }}
          path: build/firetail-extension-${{ matrix.arch }}-${{ env.RELEASE_VERSION }}.zip
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: build/firetail-extension-${{ matrix.arch }}-${{ env.RELEASE_VERSION }}.zip
          asset_name: firetail-extension-${{ matrix.arch }}-${{ env.RELEASE_VERSION }}
          asset_content_type: application/zip

  publish-package:
    runs-on: ubuntu-latest
    needs: build-package
    strategy:
      matrix:
        aws-region: [ 'eu-west-1', 'eu-west-2', 'ap-southeast-1', 'ap-southeast-2', 'us-west-1', 'us-west-2', 'us-east-1' ]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ matrix.aws-region }}
          role-to-assume: arn:aws:iam::247286868737:role/firetail-prod-github-release-access
          role-session-name: github

      - uses: actions/checkout@v3

      - name: Set RELEASE_VERSION
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Download amd64 package artifact
        uses: actions/download-artifact@v3
        with:
          name: firetail-lambda-extension-amd64-${{ env.RELEASE_VERSION }}
          path: build

      - name: Download arm64 package artifact
        uses: actions/download-artifact@v3
        with:
          name: firetail-lambda-extension-arm64-${{ env.RELEASE_VERSION }}
          path: build

      - name: Publish amd64 layer to AWS
        run: |
          AWS_LAYER_VERSION=$(make publish ARCH=amd64 VERSION=$RELEASE_VERSION AWS_REGION=${{ matrix.aws-region }})
          make public ARCH=amd64 AWS_LAYER_VERSION=$AWS_LAYER_VERSION VERSION=$RELEASE_VERSION AWS_REGION=${{ matrix.aws-region }}

      - name: Publish arm64 layer to AWS
        run: |
          AWS_LAYER_VERSION=$(make publish ARCH=arm64 VERSION=$RELEASE_VERSION AWS_REGION=${{ matrix.aws-region }})
          make public ARCH=arm64 AWS_LAYER_VERSION=$AWS_LAYER_VERSION VERSION=$RELEASE_VERSION AWS_REGION=${{ matrix.aws-region }}
