name: Build from release

on:
  push:

  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
  
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build & package layers (amd64 & arm64)
        run: |
          make package ARCH=amd64

      - name: Upload package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: firetail-lambda-extension-${env.RELEASE_VERSION}
          path: build/extension-amd64.zip

  publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aws-region: [ 'eu-west-1' ]    
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v3
        with:
          name: firetail-lambda-extension-${env.RELEASE_VERSION}
          path: build/extension-amd64.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ matrix.aws-region }}
          role-to-assume: arn:aws:iam::453671210445:role/firetail-sandbox-github-release-access
          role-session-name: github

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Publish layer to AWS
        run: |
          make publish ARCH=amd64 VERSION=${env.RELEASE_VERSION} REGION=${{ matrix.aws-region }}